const SET_USER_DATA = 'SET_USER_DATA';
const LOGOUT = 'LOGOUT';
const MESSAGE_USER = 'MESSAGE_USER';
const MESSAGE_CLEARING = 'MESSAGE_CLEARING';

const ADD_TO_BASKET = 'ADD_TO_BASKET';
const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
const INCREASE_QUANTITY_BASKET = 'INCREASE_QUANTITY_BASKET';
const DECREASE_QUANTITY_BASKET = 'DECREASE_QUANTITY_BASKET';

export {
  SET_USER_DATA,
  LOGOUT,
  MESSAGE_USER,
  MESSAGE_CLEARING,
  ADD_TO_BASKET,
  REMOVE_FROM_FAVORITES,
  REMOVE_FROM_BASKET,
  INCREASE_QUANTITY_BASKET,
  DECREASE_QUANTITY_BASKET
};
